/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netducation;

import javax.swing.JOptionPane;

/**
 *
 * @author yoelt
 */
public class TambahCourseWindow extends javax.swing.JFrame {

    /**
     * Creates new form TambahCourseWindow
     */
    public TambahCourseWindow() {
        initComponents();
    }
    
    Course c = new Course();
    String courseID;
    HomeWindow h = new HomeWindow();
    
    public void setCourseLabel(String text) {
        this.courseLabel.setText(text);
        c = CourseDatabaseClass.selectQueryCourseSingular(courseID);
        if (text.contains("Baru")) {    
            this.editCourseBtn.setEnabled(false);
        }
        else {
            System.out.println("From TCW " + courseID + " " + c.getId());
            this.idCourseField.setEnabled(false);
            this.idCourseField.setText(courseID);
            this.addCourseBtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseLabel = new javax.swing.JLabel();
        idCourseLabel = new javax.swing.JLabel();
        namaCourseLabel = new javax.swing.JLabel();
        minPoinLabel = new javax.swing.JLabel();
        poinDapatLabel = new javax.swing.JLabel();
        idCourseField = new javax.swing.JTextField();
        namaCourseField = new javax.swing.JTextField();
        minPoinField = new javax.swing.JTextField();
        poinDapatField = new javax.swing.JTextField();
        addCourseBtn = new javax.swing.JButton();
        editCourseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        courseLabel.setText(" ");

        idCourseLabel.setText("ID Course");

        namaCourseLabel.setText("Nama Course");

        minPoinLabel.setText("Minimum Poin untuk ikut");

        poinDapatLabel.setText("Poin yang didapat");

        addCourseBtn.setText("ADD");
        addCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseBtnActionPerformed(evt);
            }
        });

        editCourseBtn.setText("EDIT");
        editCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCourseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCourseLabel)
                            .addComponent(namaCourseLabel)
                            .addComponent(minPoinLabel)
                            .addComponent(poinDapatLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaCourseField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minPoinField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poinDapatField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCourseField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(editCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCourseLabel)
                    .addComponent(idCourseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaCourseLabel)
                    .addComponent(namaCourseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minPoinLabel)
                    .addComponent(minPoinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poinDapatLabel)
                    .addComponent(poinDapatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCourseBtn)
                    .addComponent(editCourseBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseBtnActionPerformed
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        String id = this.idCourseField.getText();
        String nama = this.namaCourseField.getText();
        int poinMin = Integer.parseInt(this.minPoinField.getText());
        int poinDapat = Integer.parseInt(this.poinDapatField.getText());
        int res = CourseLogicClass.insertCourseValidation(id, nama, poinMin, poinDapat);
        System.out.println(id + " " + nama + " " + poinMin + " " + poinDapat + " ");
        switch(res) {
            case 0: JOptionPane.showMessageDialog(rootPane, "BERHASIL MENAMBAHKAN COURSE", "Course Added", JOptionPane.OK_OPTION); this.setVisible(false); break;
            case 1: JOptionPane.showMessageDialog(rootPane, "ID SUDAH ADA, SILAHKAN COBA LAGI", "Error", JOptionPane.ERROR_MESSAGE); break;
            case 2: JOptionPane.showMessageDialog(rootPane, "NAMA SUDAH ADA, SILAHKAN COBA LAGI", "Error", JOptionPane.ERROR_MESSAGE); break;
        }
        
    }//GEN-LAST:event_addCourseBtnActionPerformed

    private void editCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCourseBtnActionPerformed
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        String nama = this.namaCourseField.getText();
        int poinMin = Integer.parseInt(this.minPoinField.getText());
        int poinDapat = Integer.parseInt(this.poinDapatField.getText());
        int res = CourseLogicClass.editCourseValidation(courseID, nama, poinMin, poinDapat);
        switch(res) {
            case 0: JOptionPane.showMessageDialog(rootPane, "BERHASIL MENGUBAH COURSE", "Course Edited", JOptionPane.OK_OPTION); this.setVisible(false); break;
            case 2: JOptionPane.showMessageDialog(rootPane, "NAMA SUDAH ADA, SILAHKAN COBA LAGI", "Error", JOptionPane.ERROR_MESSAGE); break;
        }
        h.getCourseTable().repaint();
    }//GEN-LAST:event_editCourseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahCourseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseBtn;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JButton editCourseBtn;
    private javax.swing.JTextField idCourseField;
    private javax.swing.JLabel idCourseLabel;
    private javax.swing.JTextField minPoinField;
    private javax.swing.JLabel minPoinLabel;
    private javax.swing.JTextField namaCourseField;
    private javax.swing.JLabel namaCourseLabel;
    private javax.swing.JTextField poinDapatField;
    private javax.swing.JLabel poinDapatLabel;
    // End of variables declaration//GEN-END:variables
}
