/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netducation;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yoelt
 */
public class TambahCourseWindow extends javax.swing.JFrame {

    /**
     * Creates new form TambahCourseWindow
     */
    public TambahCourseWindow() {
        initComponents();
    }
    
    Course c = new Course();
    String courseID;
    HomeWindow h = new HomeWindow();
    Users x;
    String path = "";
    
    public void setCourseLabel(String text) {
        this.courseLabel.setText(text);
        c = CourseDatabaseClass.selectQueryCourseSingular(courseID);
        if (text.contains("Baru")) {    
            this.editCourseBtn.setEnabled(false);
        }
        else {
            System.out.println("From TCW " + courseID + " " + c.getId());
            this.idCourseField.setEnabled(false);
            this.idCourseField.setText(courseID);
            this.addCourseBtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        courseLabel = new javax.swing.JLabel();
        idCourseLabel = new javax.swing.JLabel();
        namaCourseLabel = new javax.swing.JLabel();
        minPoinLabel = new javax.swing.JLabel();
        poinDapatLabel = new javax.swing.JLabel();
        idCourseField = new javax.swing.JTextField();
        namaCourseField = new javax.swing.JTextField();
        minPoinField = new javax.swing.JTextField();
        poinDapatField = new javax.swing.JTextField();
        addCourseBtn = new javax.swing.JButton();
        editCourseBtn = new javax.swing.JButton();
        browseFileCourse = new javax.swing.JButton();
        namaFileLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        courseLabel.setText(" ");

        idCourseLabel.setText("ID Course");

        namaCourseLabel.setText("Nama Course");

        minPoinLabel.setText("Minimum Poin untuk ikut");

        poinDapatLabel.setText("Poin yang didapat");

        addCourseBtn.setText("ADD");
        addCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseBtnActionPerformed(evt);
            }
        });

        editCourseBtn.setText("EDIT");
        editCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCourseBtnActionPerformed(evt);
            }
        });

        browseFileCourse.setText("Browse...");
        browseFileCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFileCourseActionPerformed(evt);
            }
        });

        namaFileLabel.setText("Select File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idCourseLabel)
                                    .addComponent(namaCourseLabel)
                                    .addComponent(minPoinLabel)
                                    .addComponent(poinDapatLabel))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(namaCourseField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(minPoinField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poinDapatField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idCourseField))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(namaFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addCourseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(browseFileCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCourseLabel)
                    .addComponent(idCourseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaCourseLabel)
                    .addComponent(namaCourseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minPoinLabel)
                    .addComponent(minPoinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poinDapatLabel)
                    .addComponent(poinDapatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseFileCourse)
                    .addComponent(namaFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCourseBtn)
                    .addComponent(editCourseBtn))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseBtnActionPerformed
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        String id = this.idCourseField.getText();
        String nama = this.namaCourseField.getText();
        int poinMin = Integer.parseInt(this.minPoinField.getText());
        int poinDapat = Integer.parseInt(this.poinDapatField.getText());
        int res = 0;
        try {
            res = CourseLogicClass.insertCourseValidation(id, nama, poinMin, poinDapat, x, path);
        } catch (IOException ex) {
            Logger.getLogger(TambahCourseWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(path);
        System.out.println(id + " " + nama + " " + poinMin + " " + poinDapat + " ");
        switch(res) {
            case 0: JOptionPane.showMessageDialog(rootPane, "BERHASIL MENAMBAHKAN COURSE", "Course Added", JOptionPane.INFORMATION_MESSAGE); this.setVisible(false); break;
            case 1: JOptionPane.showMessageDialog(rootPane, "ID SUDAH ADA, SILAHKAN COBA LAGI", "Error", JOptionPane.ERROR_MESSAGE); break;
            case 2: JOptionPane.showMessageDialog(rootPane, "NAMA SUDAH ADA, SILAHKAN COBA LAGI", "Error", JOptionPane.ERROR_MESSAGE); break;
        }
        
    }//GEN-LAST:event_addCourseBtnActionPerformed

    private void editCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCourseBtnActionPerformed
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        String nama = this.namaCourseField.getText();
        int poinMin = Integer.parseInt(this.minPoinField.getText());
        int poinDapat = Integer.parseInt(this.poinDapatField.getText());
        int res = CourseLogicClass.editCourseValidation(courseID, nama, poinMin, poinDapat, path);
        switch(res) {
            case 0: JOptionPane.showMessageDialog(rootPane, "BERHASIL MENGUBAH COURSE", "Course Edited", JOptionPane.INFORMATION_MESSAGE); this.setVisible(false); break;
            case 2: JOptionPane.showMessageDialog(rootPane, "NAMA SUDAH ADA, SILAHKAN COBA LAGI", "Error", JOptionPane.ERROR_MESSAGE); break;
        }
        h.getCourseTable().repaint();
    }//GEN-LAST:event_editCourseBtnActionPerformed

    private void browseFileCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFileCourseActionPerformed
        this.jFileChooser1.showOpenDialog(this);
        this.jFileChooser1.setApproveButtonText("Save");
        path = this.jFileChooser1.getSelectedFile().getAbsolutePath();
        System.out.println(path);
        this.namaFileLabel.setText(this.jFileChooser1.getSelectedFile().getName());
        
//        this.jFileChooser1.getSelectedFile().getAbsolutePath();
//        File curFile = this.jFileChooser1.getSelectedFile();
//        File newFile = new File("C:\\Users\\yoelt\\Documents\\5th Semester\\RPL - Software Engineering\\PROJECT RPL\\CoursePDF");
//        FileUtils.copyDirectory(curFile, newFile);
    }//GEN-LAST:event_browseFileCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahCourseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseBtn;
    private javax.swing.JButton browseFileCourse;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JButton editCourseBtn;
    private javax.swing.JTextField idCourseField;
    private javax.swing.JLabel idCourseLabel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JTextField minPoinField;
    private javax.swing.JLabel minPoinLabel;
    private javax.swing.JTextField namaCourseField;
    private javax.swing.JLabel namaCourseLabel;
    private javax.swing.JLabel namaFileLabel;
    private javax.swing.JTextField poinDapatField;
    private javax.swing.JLabel poinDapatLabel;
    // End of variables declaration//GEN-END:variables
}
